# 服务器配置
server:
  port: 8080

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/login_system?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lzc2025666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 20
      minimum-idle: 5

# MyBatis Plus配置
mybatis-plus:
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 配置SQL打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  # 密钥
  secret: mySecretKey
  # token过期时间(单位：毫秒)，这里设置为24小时
  expiration: 86400000
  # token在header中的名称
  header: Authorization

# 微信支付配置
wx:
  pay:
    # 微信支付商户号
    mch-id: your_mch_id
    # 微信支付商户密钥
    mch-key: your_mch_key
    # 微信支付appId
    app-id: your_app_id
    # 微信支付API地址
    api-url: https://api.mch.weixin.qq.com
    # 支付通知地址
    notify-url: http://localhost:8080/api/payment/wechat/notify

# 支付宝支付配置
alipay:
  # 应用ID
  app-id: 9021000151617355
  # 商户私钥
  merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC72iUGP4GtCVBxgYBoteITIE5kw2akjfXmvXCNs5TSexlJ565LCAqxCeDBYcn0j0EnG6BuLBlXKsePaU0OF0mOz4eJ1JQCc//l2bkn5QB8xiWb7jRKa0LydDInJQZYdttmoaeHWP5XiajUixP4QrbxU9A6F9foOW6Fopfaz14muKoekkTRiLDS0CNKu49Thk2Z0YfcHNClLQ4wrNGFKMwyiOChPGhhTBHCcLbRJ/AynDexcM0fuTZ1UjquZjjAv4lGLCYsz7nMiWKM7mooNSfkVO6qj/0m/AqEHcWu1c4uhFRcsSWld8VWsKfOlvxoHTmWb8UrA7UEedqjUPFYG1PfAgMBAAECggEAKzLkNsad7Ivqyt9sByhkf997B6MD1K2ssc44tu1oOOsECsHTi/+ibcoGvJHfXnUfF34763oKrcfxsmIVzTq/uK6yzZhsHRBN9a6W7Ly12vu6JFyn+8Ek2RqteeECz48trzFXlEF74+eNQqtlAT9eUKrkhKd9CDNE3khgwXnUffSuKbdZPZ8m5nFk//9QkX0JYIq/cNiuUu655+YP84PPla1VFF6crqw6Ky9CgTb0RhGAfZfS40KmKWXIHwNNgueklmXia6ZTHX2oSp+lroHS/5WnOS5Xpcc68XiXQTUmoxlQJcLQEIuwFglCrbqBfhahsEg8114eiuk0JcH7EscgGQKBgQDwVv0gAWk2io6z3PJ0t4xTrbLNpUzIMftjh/gA+hcDzLs76DLO3UsGmmEBfAe+T6N3zh+BJSRK/iQ7q7BGUr4di36DCr/1RxCLHTYYoasPq/f2tUoLnkoGf6UWudB5z6BEuggO4m3bsB4KCDNAO0gYWMqk++kIyrMRlvp58JLIgwKBgQDIF6FS3P3rweOlhgCsY4VVd+6N/SANaqHQDVm4RuyzOXh2InFIb3PFgXyc0DNQJ98s/TdeGgxTeL5NeUAsHI3FHDjtfWasYxQmkhWRX9GzOtlcvYx01fNzlpy3SKeABWh2/tzVAH/Nut2MLWh8yg4oEhxIQuTT7A059OCnDhSQdQKBgGXfSW2+i11N/8znc3Hbt0Rk1OxsC46z+O2oXYv0dbrrldV/x8F9dWa4GzQo4ZNeaFjI6vuvxaFv9eXBEXfNbL5TOW3MKa+Kzs1YtWxdYofDCdjt4RPppVD52/01B9QKGNHo1K+SdKRxE1qHPUoVlqqTQFoMWSub16k2CLeVLHKHAoGAYldK0IEQw1hN3EJZ/mADXhhNxLdNk4p+8NQ+7lTdbNCoJdeTubgdPEsBxciGD7Uo+OGS3ssKl9PWJBmdspBuFRxj1kU1uzAO7U4LD6H6XI5l2jDG4X1t47d4WpR4znDaAPIN8xoFtkVLMeP3YK2l+4e7IsDN2mI/teZmq3Q+IykCgYAnPB5KlpWwxlX6Ayhq3rQE4YqoEA3AbQU8tzmFAQPUh0YBEoAwbq4bsrwsqYSNImcRgfSIlZN+NUYtpbkPBtJVr0xHxpgNhGruGcn4QIgPqOKMGWporwFXGXezor7AIaIS87GX0StlwRwUYu5DxcWggCUN9cOvzGuM+E+M6RydBQ==
  # 支付宝公钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzkyzdTEBNaxDTQrLPqjiSA1vPo7InzYG6U5jjPc+49IxVuiSTchVdg9atYUCo5eLqZdqLBpGNg4XB5yuFLmy/eOPUZA8FznvNH/iOZooow9IymjPvf9wN5ho5241VoZCcgVpIBkiIKjPgrO1kJq3t59+l5XgLheUM0XNjDnEl3QSdU3WRfphPXwEafFnErT8F2jWjNii8vQHDdAVxQEWEn2KxC2HjtCHYVInbyrkpiZ76JEolWeVRAeBV5XyK3ldQ8ook7NDZIcEBvsqxBEH9/Ep+MQxqjgWpo3+CRZtZO5T/Ud48XRaV9nVAhDZFcGZbw6l+IbDC0zTWN9vftz+EwIDAQAB
  # 签名类型
  sign-type: RSA2
  # 字符编码格式
  charset: UTF-8
  # 支付宝网关地址
#  gateway-url: https://openapi.alipay.com/gateway.do
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 支付成功后的回调地址
  return-url: http://localhost:8080/api/payment/alipay/return
  # 支付成功后的异步通知地址
  notify-url: http://localhost:8080/api/payment/alipay/notify